import {prisma} from '@/lib/db';
import {fulfillBundleShopGH,fulfillBundleShopGHAFA,fulfillMuviinAirtime,fulfillMuviinChecker,fulfillRefer2Bundle,registerRefer2BundleAFA} from '@/lib/providers';
import {checkerTypeFor, dataPlanFromName} from '@/lib/product-rules';
import {siteUrl} from '@/lib/site-url';
export async function startFulfillment(orderId:string){const order=await prisma.order.findUnique({where:{id:orderId},include:{OrderItem:{include:{Product:true}}}});if(!order)return;for(const item of order.OrderItem){if(item.fulfillment!=='PENDING')continue;if(item.source==='BUNDLESHOPGH'&&/afa/i.test(item.Product.category)){const meta=(item.metadata??{}) as {fullName?:string;idCardNumber?:string;location?:string};try{const result=await fulfillBundleShopGHAFA({phone:order.customerPhone,fullName:meta.fullName,idCardNumber:meta.idCardNumber,location:meta.location,callback:`${siteUrl()}/api/webhooks/bundleshopgh?token=${process.env.BUNDLESHOPGH_WEBHOOK_TOKEN??''}`});if(result.reference)await prisma.orderItem.update({where:{id:item.id},data:{externalRef:result.reference}});}catch{/* Pending for admin/manual processing. */}}
if(item.source==='BUNDLESHOPGH'&&/data bundle/i.test(item.Product.category)){const size=Number(item.Product.name.match(/(\d+(?:\.\d+)?)\s*GB/i)?.[1]);if(!size||!item.Product.network)continue;try{const result=await fulfillBundleShopGH({phone:order.customerPhone,size,network:item.Product.network,callback:`${siteUrl()}/api/webhooks/bundleshopgh?token=${process.env.BUNDLESHOPGH_WEBHOOK_TOKEN??''}`}) as {id?:string;data?:{id?:string}};const externalRef=result.id??result.data?.id;if(externalRef)await prisma.orderItem.update({where:{id:item.id},data:{externalRef}})}catch{/* Pending for admin retry. */}}
if(item.source==='REFER2BUNDLE'&&/afa/i.test(item.Product.category)){const meta=(item.metadata??{}) as {fullName?:string;idCardNumber?:string;location?:string};if(!meta.fullName||!meta.idCardNumber||!meta.location)continue;try{const result=await registerRefer2BundleAFA({fullName:meta.fullName,phone:order.customerPhone,idCardNumber:meta.idCardNumber,location:meta.location,idempotencyKey:`DM_afa_${item.id}`});if(result.reference)await prisma.orderItem.update({where:{id:item.id},data:{externalRef:result.reference}});}catch{/* Pending for polling/retry. */}}
if(item.source==='REFER2BUNDLE'&&/data bundle/i.test(item.Product.category)){const dataPlan=dataPlanFromName(item.Product.name);if(!dataPlan||!item.Product.network)continue;try{const result=await fulfillRefer2Bundle({network:item.Product.network,dataPlan,beneficiary:order.customerPhone});if(result.reference)await prisma.orderItem.update({where:{id:item.id},data:{externalRef:result.reference}});}catch{/* Pending for polling/retry. */}}
if(item.source==='MUVIIN'&&/airtime/i.test(item.Product.category)){const extRef=`DM_muviin_${item.id}`;const network={MTN:'mtn',Telecel:'telecel',AirtelTigo:'at'}[item.Product.network??'']??'';if(!network)continue;try{await prisma.orderItem.update({where:{id:item.id},data:{externalRef:extRef}});await fulfillMuviinAirtime({phone:order.customerPhone,amount:Number(item.unitPrice),network,extRef});}catch{/* Pending for controlled status polling/retry. */}}
if(item.source==='MUVIIN'&&/result checker/i.test(item.Product.category)){const extRef=`DM_checker_${item.id}`;try{const result=await fulfillMuviinChecker({checkerType:checkerTypeFor(item.Product),extRef});const payload=(result as {status?:unknown}).status!==undefined?result:{received:true};await prisma.orderItem.update({where:{id:item.id},data:{externalRef:extRef,metadata:{...(item.metadata as object|null??{}),checkerRequest:payload} as never}});}catch{/* Pending for admin retry / polling. */}}
}}
