'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';
export default function SignIn(){const router=useRouter();const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [next,setNext]=useState('/account');
const [adminOpen,setAdminOpen]=useState(false);const [adminPhone,setAdminPhone]=useState('');const [adminPass,setAdminPass]=useState('');const [adminKey,setAdminKey]=useState('');const [adminMsg,setAdminMsg]=useState('');const [adminBusy,setAdminBusy]=useState(false);
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{const n=new URLSearchParams(window.location.search).get('next');if(n&&n.startsWith('/'))setNext(n);const h=window.location.hash;if(h==='#google-not-configured')setError('Google sign-in is not configured yet (set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET).');if(h==='#google-failed')setError('Google sign-in failed. Try again or use your phone number.');},[]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,password})});const data=await r.json();if(!r.ok)throw new Error(data.message);router.push(next);}catch(e){setError(e instanceof Error?e.message:'Could not sign in.')}finally{setBusy(false)}};
const recoverAdmin=async(e:React.FormEvent)=>{e.preventDefault();setAdminBusy(true);setAdminMsg('');try{const r=await fetch('/api/auth/recover-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:adminPhone,newPassword:adminPass,recoveryKey:adminKey})});const d=await r.json();if(!r.ok)throw new Error(d.message);setAdminMsg(d.data.message);setAdminKey('');}catch(e){setAdminMsg(e instanceof Error?e.message:'Could not process recovery.')}finally{setAdminBusy(false)}};
return <main className="auth"><section className="authBrand"><div className="logo"><span>Digi</span><b>Mart</b></div><p>ONE MARKETPLACE. EVERY NEED.</p><h1>Welcome back to a simpler way to shop.</h1><span>Access your orders, wallet, reseller store and marketplace account in one secure place.</span><div className="authMarks"><b>🔒 Secure account access</b><b>◴ Order tracking</b><b>◉ Wallet & rewards</b></div></section><section className="authForm"><Link href="/">← Back to marketplace</Link><div><p className="eyebrow">SIGN IN</p><h2>Welcome back</h2><span>Enter your account details to continue.</span></div><form onSubmit={submit}><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="055 123 4567" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Enter your password" required/></label><div className="authOptions"><label><input type="checkbox"/> Remember me</label><Link href="/support" style={{color:'#1647a6',fontWeight:800,fontSize:12,textDecoration:'none'}}>Forgot password?</Link></div>{error&&<p className="authError">{error}</p>}<button disabled={busy} className="authSubmit">{busy?'Signing in…':'Sign in to DigiMart'}</button><a className="google" href="/api/auth/google">G Continue with Google</a></form><p className="authSwitch">New to DigiMart? <Link href="/sign-up">Create a free account</Link></p>
<div className="adminRecovery"><button type="button" className="adminToggle" onClick={()=>setAdminOpen(!adminOpen)}>{adminOpen?'▲':'▼'} Admin access &amp; recovery</button>{adminOpen&&<form onSubmit={recoverAdmin}><p>Create or promote an ADMIN account. Requires the server-side recovery key (ADMIN_RECOVERY_KEY in your environment).</p><label>Admin phone number<input value={adminPhone} onChange={e=>setAdminPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="054 000 0000" required/></label><label>New password (min 8 chars)<input value={adminPass} onChange={e=>setAdminPass(e.target.value)} type="password" required/></label><label>Recovery key<input value={adminKey} onChange={e=>setAdminKey(e.target.value)} type="password" placeholder="ADMIN_RECOVERY_KEY value" required/></label>{adminMsg&&<p className="authError">{adminMsg}</p>}<button disabled={adminBusy}>{adminBusy?'Processing…':'Create / promote admin'}</button></form>}</div>
</section></main>}
