'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Msg={id:string;senderRole:string;senderName:string;message:string;createdAt:string};
type Ticket={id:string;topic:string;orderNo?:string;message:string;status:string;createdAt:string};
export default function AdminSupport(){const [tickets,setTickets]=useState<Ticket[]>([]);const [loading,setLoading]=useState(true);const [openId,setOpenId]=useState('');const [msgs,setMsgs]=useState<Msg[]>([]);const [reply,setReply]=useState('');const [close,setClose]=useState(false);
const load=()=>fetch('/api/support/tickets').then(r=>r.json()).then(r=>setTickets(r.data??[])).finally(()=>setLoading(false));
useEffect(()=>{load()},[]);
const open=async(id:string)=>{if(openId===id){setOpenId('');return}setOpenId(id);setMsgs([]);const r=await fetch(`/api/support/tickets/${id}/messages`);const d=await r.json();if(r.ok)setMsgs(d.data.messages);};
const send=async(id:string)=>{if(!reply.trim())return;const r=await fetch(`/api/support/tickets/${id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:reply,close})});if(r.ok){setReply('');setOpenId('');load();}};
return <main className="supportAdmin"><header><div><p>ADMIN / CUSTOMER CARE</p><h1>Support requests</h1></div><Link href="/admin" className="btnLike">← Overview</Link></header><section className="supportMetrics"><article><b>{tickets.filter(t=>t.status!=='CLOSED').length}</b><span>Open tickets</span></article><article><b>{tickets.filter(t=>t.status==='ANSWERED').length}</b><span>Answered</span></article><article><b>{tickets.filter(t=>t.status==='CLOSED').length}</b><span>Closed</span></article></section><section className="ticketList"><div className="heading"><div><p className="eyebrow">INBOX</p><h2>Customer requests</h2></div><button onClick={load}>Refresh</button></div>{loading?<p className="empty">Loading support requests…</p>:tickets.length?tickets.map(t=><article key={t.id} style={{display:'block'}}><div className="threadHead" onClick={()=>open(t.id)}><div>◉</div><span><b>{t.topic.replaceAll('_',' ')}</b><small>{t.id}{t.orderNo?` · ${t.orderNo}`:''} · {new Date(t.createdAt).toLocaleString()}</small></span><em className={`badge ${t.status==='CLOSED'?'failed':t.status==='ANSWERED'?'completed':'pending'}`}>{t.status}</em></div>
{openId===t.id&&<div className="threadBody">{msgs.map(m=><div key={m.id} className={m.senderRole==='SUPPORT'?'msg staff':'msg'}><b>{m.senderName}</b><p>{m.message}</p><small>{new Date(m.createdAt).toLocaleString('en-GB')}</small></div>)}
<div className="replyRow"><input value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…"/><button onClick={()=>send(t.id)}>Send</button></div><label style={{display:'flex',gap:7,alignItems:'center',fontSize:12,fontWeight:700,margin:'8px 0 0'}}><input type="checkbox" checked={close} onChange={e=>setClose(e.target.checked)}/> Close ticket after sending</label></div>}
</article>):<p className="empty">No support requests yet. New tickets will appear here.</p>}</section></main>}
