import {NextResponse} from 'next/server';
import {z} from 'zod';
import {clientIp,limited} from '@/lib/rate-limit';
import {initiateMoolreCollection} from '@/lib/providers';
import {prisma} from '@/lib/db';
import {readSession} from '@/lib/session';
import {computePaymentFee} from '@/lib/fees';

const bodySchema=z.object({customerPhone:z.string().regex(/^0\d{9}$/,'Use a valid 10-digit Ghana phone number.'),provider:z.enum(['MTN','Telecel','AirtelTigo']),resellerSlug:z.string().optional(),sellerSlug:z.string().optional(),items:z.array(z.object({productId:z.string(),qty:z.number().int().min(1).max(10),metadata:z.record(z.string(),z.unknown()).default({})})).min(1).max(20),idempotencyKey:z.string().min(12).max(200),couponCode:z.string().min(3).max(30).optional(),deliveryZoneId:z.string().optional(),deliveryMethod:z.enum(['DELIVERY','PICKUP','SELLER_SHIPPING','SCHEDULED_SERVICE']).optional(),deliveryAddressId:z.string().optional(),deliveryAddress:z.object({recipientName:z.string().min(2).max(120),phone:z.string().regex(/^0\d{9}$/),address:z.string().min(4).max(300),city:z.string().min(2).max(80)}).optional()});
const orderNo=()=>`DM-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
export async function POST(request:Request){const gate=limited(`checkout:${clientIp(request)}`,5,60_000);if(!gate.allowed)return NextResponse.json({status:'error',message:'Too many checkout attempts. Please wait before trying again.'},{status:429,headers:{'Retry-After':String(gate.retryAfter)}});const parsed=bodySchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({status:'error',message:parsed.error.issues[0]?.message??'Invalid checkout request.'},{status:400});const token=request.headers.get('cookie')?.match(/digimart_session=([^;]+)/)?.[1];const session=token?await readSession(decodeURIComponent(token)):null;const products=await prisma.product.findMany({where:{id:{in:parsed.data.items.map(i=>i.productId)},inStock:true,isExcluded:false}});if(products.length!==parsed.data.items.length)return NextResponse.json({status:'error',message:'One or more selected products are unavailable.'},{status:409});
let sellerStoreId:string|undefined;
if(parsed.data.sellerSlug){const seller=await prisma.seller.findUnique({where:{storeSlug:parsed.data.sellerSlug}});if(!seller||!seller.approved)return NextResponse.json({status:'error',message:'This seller store is unavailable.'},{status:404});sellerStoreId=seller.id;
for(const p of products){if(p.sellerId&&p.sellerId!==sellerStoreId&&!(p.approvalStatus==='APPROVED'&&p.onPlatform))return NextResponse.json({status:'error',message:`${p.name} is not available in this store.`},{status:409});}}
else{for(const p of products){if(p.sellerId&&!(p.approvalStatus==='APPROVED'&&p.onPlatform))return NextResponse.json({status:'error',message:`${p.name} is sold exclusively in its seller's store.`},{status:409});}}
for(const p of products){if(p.approvalStatus!=='APPROVED')return NextResponse.json({status:'error',message:'One or more products are still awaiting approval.'},{status:409});}const hasPhysical=products.some(p=>p.source==='ADMIN');let resellerId:string|undefined;if(parsed.data.resellerSlug){const reseller=await prisma.reseller.findUnique({where:{storeSlug:parsed.data.resellerSlug}});if(!reseller||reseller.status!=='APPROVED')return NextResponse.json({status:'error',message:'This reseller store is unavailable.'},{status:404});resellerId=reseller.id;}
if(hasPhysical&&!parsed.data.deliveryMethod)return NextResponse.json({status:'error',message:'Choose a delivery method (delivery or pickup) for physical items.'},{status:400});
const markupByProduct=new Map<string,number>();let defaultMarkup=0;
if(resellerId){const rr=await prisma.reseller.findUnique({where:{id:resellerId},select:{defaultMarkupPct:true}});defaultMarkup=Number(rr?.defaultMarkupPct??0);const mks=await prisma.resellerProductMarkup.findMany({where:{resellerId}});for(const m of mks)markupByProduct.set(m.productId,Number(m.markupPct));}
const unitPriceFor=(p:{id:string;basePrice:unknown})=>Math.round(Number(p.basePrice)*(1+(markupByProduct.get(p.id)??defaultMarkup)/100)*100)/100;
const subtotal=parsed.data.items.reduce((sum,item)=>sum+unitPriceFor(products.find(p=>p.id===item.productId)!)*item.qty,0);let discount=0;let couponCode:string|undefined;if(parsed.data.couponCode){const coupon=await prisma.coupon.findUnique({where:{code:parsed.data.couponCode.toUpperCase()}});const now=new Date();if(coupon&&coupon.storeSlug&&coupon.storeSlug!==(parsed.data.sellerSlug??parsed.data.resellerSlug??null))return NextResponse.json({status:'error',message:'This coupon is only valid in its own store.'},{status:409});if(!coupon||!coupon.active||(coupon.startsAt&&coupon.startsAt>now)||(coupon.endsAt&&coupon.endsAt<now)||(coupon.usageLimit!==null&&coupon.usageCount>=coupon.usageLimit)||(coupon.minimumOrder&&subtotal<Number(coupon.minimumOrder)))return NextResponse.json({status:'error',message:'Coupon is not available for this order.'},{status:409});discount=coupon.discountType==='PERCENTAGE'?subtotal*Number(coupon.discountValue)/100:Math.min(subtotal,Number(coupon.discountValue));couponCode=coupon.code;}
let deliveryFee=0;let deliveryZoneId:string|undefined;let deliveryAddressId:string|undefined;let deliveryAddressSnapshot:object|null=null;const deliveryMethod=parsed.data.deliveryMethod;
if(deliveryMethod==='DELIVERY'){if(!parsed.data.deliveryZoneId)return NextResponse.json({status:'error',message:'Select a delivery zone.'},{status:400});const zone=await prisma.deliveryZone.findUnique({where:{id:parsed.data.deliveryZoneId}});if(!zone||!zone.active)return NextResponse.json({status:'error',message:'Selected delivery zone is unavailable.'},{status:400});
if(parsed.data.deliveryAddressId&&session){const address=await prisma.customerAddress.findFirst({where:{id:parsed.data.deliveryAddressId,userId:session.id}});if(!address)return NextResponse.json({status:'error',message:'Selected address is unavailable.'},{status:400});deliveryAddressId=address.id;deliveryAddressSnapshot={recipientName:address.recipientName,phone:address.phone,address:address.address,city:address.city,label:address.label};}
else if(parsed.data.deliveryAddress){const a=parsed.data.deliveryAddress;deliveryAddressSnapshot=a;if(session){const saved=await prisma.customerAddress.create({data:{id:crypto.randomUUID(),userId:session.id,label:'Delivery address',recipientName:a.recipientName,phone:a.phone,address:a.address,city:a.city,region:a.city}});deliveryAddressId=saved.id;}}
else return NextResponse.json({status:'error',message:'Enter the delivery address.'},{status:400});
deliveryFee=zone.minimumOrder&&subtotal>=Number(zone.minimumOrder)?0:Number(zone.baseFee);deliveryZoneId=zone.id;}
else if(deliveryMethod==='PICKUP'){if(!parsed.data.deliveryZoneId)return NextResponse.json({status:'error',message:'Pickup zone is required.'},{status:400});const zone=await prisma.deliveryZone.findUnique({where:{id:parsed.data.deliveryZoneId}});if(!zone||!zone.active||!zone.pickupAvailable)return NextResponse.json({status:'error',message:'Pickup is unavailable for this zone.'},{status:400});deliveryZoneId=zone.id;}
const goodsTotal=Math.max(0,subtotal-discount)+deliveryFee;const paymentFee=computePaymentFee(goodsTotal);const total=goodsTotal+paymentFee;const id=orderNo();const paymentRef=`DM_order_${id}_${Date.now()}`;
const order=await prisma.order.create({data:{id,customerId:session?.id||undefined,customerPhone:parsed.data.customerPhone,resellerId,sellerStoreId,total,discount,couponCode,deliveryFee,paymentFee,deliveryZoneId,deliveryMethod,deliveryAddressId,deliveryAddressSnapshot:deliveryAddressSnapshot as never,paymentRef,status:'PENDING',OrderItem:{create:parsed.data.items.map(item=>{const product=products.find(p=>p.id===item.productId)!;return {id:crypto.randomUUID(),Product:{connect:{id:product.id}},source:product.source,qty:item.qty,unitPrice:unitPriceFor(product),basePrice:product.basePrice,metadata:item.metadata as never}})}}});
try{const payment=await initiateMoolreCollection({payer:parsed.data.customerPhone,amount:total,channel:parsed.data.provider,externalref:paymentRef,reference:order.id});return NextResponse.json({status:'success',data:{orderId:order.id,status:'PENDING_PAYMENT',subtotal,discount,couponCode,deliveryFee,paymentFee,total,paymentReference:paymentRef,instructions:payment.instructions,mode:payment.mode,notice:'Do not mark this order paid until the verified Moolre webhook is processed.'}})}catch(error){await prisma.order.update({where:{id:order.id},data:{status:'FAILED'}});const reason=error instanceof Error&&error.message?` — ${error.message}`:'';return NextResponse.json({status:'error',message:`Payment is unavailable right now${reason}. If this keeps happening, the store owner must complete their payment-provider setup.`},{status:502})}}
